version: "2"
services:
  openldap:
    image: osixia/openldap:1.3.0
    container_name: openldap
    command: --loglevel debug --copy-service
    environment:
      LDAP_LOG_LEVEL: "256"
      # LDAP_ORGANISATION: "Example Inc."
      # LDAP_DOMAIN: "example.org"
      # LDAP_BASE_DN: ""
      # LDAP_ADMIN_PASSWORD: "admin"
      # LDAP_CONFIG_PASSWORD: "config"
      # LDAP_READONLY_USER: "false"
      # LDAP_RFC2307BIS_SCHEMA: "false"
      # LDAP_BACKEND: "mdb"
      # LDAP_TLS: "false"
      # LDAP_TLS_CRT_FILENAME: "ldap.crt"
      # LDAP_TLS_KEY_FILENAME: "ldap.key"
      # LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
      # LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      # LDAP_TLS_ENFORCE: "false"
      # LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      # LDAP_TLS_PROTOCOL_MIN: "3.1"
      # LDAP_TLS_VERIFY_CLIENT: "demand"
      # LDAP_REPLICATION: "false"
      # KEEP_EXISTING_CONFIG: "false"
      # LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      # LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    # domainname: "example.org"
    # hostname: "example.org"
